version: '3'
services:
    web:
      working_dir: /quoridor
      image: gradle:jdk11
      ports: 
        - "8080:8080"
      volumes: 
        - .:/quoridor
        - gradle-cache:/quoridor/.gradle-cache 
      command: "gradle bootRun"
      user: "${UID}:${GID}"
      environment: 
        - GRADLE_USER_HOME=/quoridor/.gradle-cache 

volumes:
   gradle-cache: {}
